env: "local" # local, dev, prod  # окружение запуска приложения
# local - локальное окружение
# dev - тестовое окружение
# prod - продакшн окружение
storage_path: "./migrations/schema.sql" # Путь до файйла с бд
http_server:
  address: "0.0.0.0:8080" # Адрес http сервера
  timeout: 4s # Таймаут http сервера (время на чтение запроса и на отправку ответа)
  idle_timeout: 60s # Таймаут idle http сервера (время жизни соединения с клиентов)