name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          docker compose --version

      - name: Build and run containers
        run: |
          docker compose up -d --build

      - name: Run go build
        run: go build ./...

      - name: Run go test
        run: go test -v ./...

      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose down
